#!/usr/bin/env python3
from __future__ import annotations
"""
tools/report/fix_generator.py
Generates actionable fix artifacts from scan results:

1. .env.example — template for all detected hardcoded secrets
2. .gitignore audit — warns if .env is not ignored
3. Fix prompt — copy-paste prompt for Cursor/Claude to fix all findings

This bridges the gap between "I know what's wrong" and "I know how to fix it"
for vibe coders who don't write fixes themselves — they ask their AI to fix it.
"""

import json
from pathlib import Path


def generate_env_example(secrets: list[dict]) -> str:
    """Generate .env.example from detected secrets."""
    if not secrets:
        return ""

    lines = [
        "# .env.example — Generated by VibeSafe",
        "# Copy this file to .env and fill in your actual values.",
        "# NEVER commit .env to git.",
        "",
    ]

    # Map secret types to env var names
    type_to_var = {
        "openai_key": "OPENAI_API_KEY",
        "aws_access_key": "AWS_ACCESS_KEY_ID",
        "aws_secret_key": "AWS_SECRET_ACCESS_KEY",
        "github_token": "GITHUB_TOKEN",
        "stripe_secret": "STRIPE_SECRET_KEY",
        "stripe_publishable": "STRIPE_PUBLISHABLE_KEY",
        "google_api_key": "GOOGLE_API_KEY",
        "slack_token": "SLACK_BOT_TOKEN",
        "slack_webhook": "SLACK_WEBHOOK_URL",
        "jwt_token": "JWT_SECRET",
        "supabase_key": "SUPABASE_ANON_KEY",
        "db_url": "DATABASE_URL",
        "generic_api_key": "API_KEY",
        "generic_password": "PASSWORD",
    }

    seen_vars = set()
    for secret in secrets:
        secret_type = secret.get("type", "generic")
        var_name = type_to_var.get(secret_type, secret_type.upper())
        if var_name not in seen_vars:
            seen_vars.add(var_name)
            lines.append(f"{var_name}=your_{var_name.lower()}_here")

    return "\n".join(lines) + "\n"


def audit_gitignore(source_path: Path, has_secrets: bool) -> list[dict]:
    """Check if .env is properly gitignored."""
    findings = []
    gitignore = source_path / ".gitignore"

    if not has_secrets:
        return findings

    if not gitignore.exists():
        findings.append({
            "type": "missing_gitignore",
            "severity": "HIGH",
            "message": "No .gitignore file found. Secrets in .env files will be committed to git.",
            "fix": "Create .gitignore with at least: .env, .env.local, .env.production",
        })
        return findings

    content = gitignore.read_text()
    patterns_needed = [".env"]
    for pattern in patterns_needed:
        # Check if .env is ignored (exact or wildcard)
        if pattern not in content and "*.env" not in content:
            findings.append({
                "type": "env_not_gitignored",
                "severity": "HIGH",
                "message": f"'{pattern}' is not in .gitignore. Secrets will be committed to git.",
                "fix": f"Add '{pattern}' to .gitignore",
            })

    return findings


def generate_fix_prompt(findings: list[dict]) -> str:
    """Generate a copy-paste prompt for Cursor/Claude to fix all findings."""
    if not findings:
        return ""

    lines = [
        "# VibeSafe Fix Prompt",
        "# Copy this entire prompt and paste it into Cursor/Claude/ChatGPT.",
        "# Your AI assistant will fix all the security issues found.",
        "",
        "Fix the following security vulnerabilities in my code:",
        "",
    ]

    for i, f in enumerate(findings, 1):
        file_info = f""
        if f.get("file"):
            file_info = f" in `{f['file']}"
            if f.get("line"):
                file_info += f":{f['line']}"
            file_info += "`"

        lines.append(f"{i}. **{f.get('severity', 'HIGH')}**{file_info}")
        if f.get("message"):
            msg = f["message"][:150]
            lines.append(f"   Problem: {msg}")
        if f.get("fix"):
            lines.append(f"   Fix: {f['fix']}")
        lines.append("")

    lines.extend([
        "Rules:",
        "- Move all hardcoded secrets to environment variables (os.environ.get or process.env)",
        "- Use parameterized queries instead of string concatenation for SQL",
        "- Never use eval() or exec() with user input",
        "- Never use subprocess with shell=True and user input",
        "- Add input validation for all user-facing endpoints",
        "- Generate a .env.example file with placeholder values",
        "- Make sure .env is in .gitignore",
    ])

    return "\n".join(lines) + "\n"


def main():
    import argparse
    parser = argparse.ArgumentParser(description="VibeSafe Fix Generator")
    parser.add_argument("--path", required=True, help="Source code path")
    parser.add_argument("--secret-result", help="Secret scan JSON result")
    parser.add_argument("--sast-result", help="SAST SARIF result")
    parser.add_argument("--config-result", help="Config scan JSON result")
    parser.add_argument("--output-dir", help="Output directory for generated files")
    args = parser.parse_args()

    source_path = Path(args.path)
    output_dir = Path(args.output_dir) if args.output_dir else source_path
    output_dir.mkdir(parents=True, exist_ok=True)

    # Load findings
    all_findings = []
    secrets = []

    if args.secret_result and Path(args.secret_result).exists():
        data = json.loads(Path(args.secret_result).read_text())
        secrets = data.get("secrets", [])
        for s in secrets:
            all_findings.append({
                "severity": "CRITICAL",
                "file": s.get("file", ""),
                "line": s.get("line", 0),
                "message": f"Hardcoded {s.get('name', 'secret')}",
                "fix": f"Move to environment variable: os.environ.get('{s.get('type', 'SECRET').upper()}')",
            })

    if args.config_result and Path(args.config_result).exists():
        data = json.loads(Path(args.config_result).read_text())
        for f in data.get("findings", []):
            all_findings.append(f)

    # Generate .env.example
    env_example = generate_env_example(secrets)
    if env_example:
        env_path = output_dir / ".env.example"
        env_path.write_text(env_example)
        print(f"Generated: {env_path}")

    # Audit .gitignore
    gitignore_findings = audit_gitignore(source_path, bool(secrets))
    for f in gitignore_findings:
        print(f"⚠️  {f['message']}")
        all_findings.append(f)

    # Generate fix prompt
    if all_findings:
        prompt = generate_fix_prompt(all_findings)
        prompt_path = output_dir / "VIBESAFE_FIX.md"
        prompt_path.write_text(prompt)
        print(f"Generated: {prompt_path}")
        print(f"\n📋 Copy the contents of VIBESAFE_FIX.md and paste into your AI assistant.")

    # Summary
    print(json.dumps({
        "env_example_generated": bool(env_example),
        "gitignore_issues": len(gitignore_findings),
        "fix_prompt_generated": bool(all_findings),
        "total_findings_in_prompt": len(all_findings),
    }, indent=2))


if __name__ == "__main__":
    main()
